### PR TITLE
Removed deprecated image-tag annotation

### PR DESCRIPTION
**Pull request by solarkennedy**
There should be no code left trying to use this annotation

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Probably already on your radar, but SourceGraph shows it being used here: https://sourcegraph.netflix.net/stash.corp.netflix.com/GM/titus-executor@aec0fbb1d42eafc529d45779f34a1182228cb02c/-/blob/executor/runtime/types/pod.go?L433:58

**Review by aaronlehmann — APPROVED** [review]

**Comment by solarkennedy** [comment]
Whoa! How is this working in real life???
I'l fix that asap.

**Comment by solarkennedy** [comment]
After this is merged I'll make a PR to titus-executor to pick up the change.

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
