### PR TITLE
High scale network mode annotations for security groups and subnetIds

### PR DESCRIPTION
**Pull request by MyUmmaGumma**
Create a static config for high scale network mode annotations for security groups and subnet Ids.

### CODE REVIEW

**Comment by sargun** [comment]
1. This configuration should be a CRD
2. Are you not going to overwrite the sgs / subnets on the pod?

**Comment by MyUmmaGumma** [comment]
> 1. This configuration should be a CRD
> 2. Are you not going to overwrite the sgs / subnets on the pod?

I am following @solarkennedy 's comment here (which I might have misunderstood) https://jira.netflix.net/browse/HN-21?focusedCommentId=5172180&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5172180

I planned to add the changes here and then overwrite the sgs and subnets in the titus-agent-controller. Have I misunderstood?

**Comment by solarkennedy** [comment]
> > 1. This configuration should be a CRD
> > 2. Are you not going to overwrite the sgs / subnets on the pod?
> 
> I am following @solarkennedy 's comment here (which I might have misunderstood) https://jira.netflix.net/browse/HN-21?focusedCommentId=5172180&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5172180
> 
> I planned to add the changes here and then overwrite the sgs and subnets in the titus-agent-controller. Have I misunderstood?

Yea I think you misunderstood. We can use the existing annotations to *setting* SG,sub, we don't need new annotations.

Config for what those settings should *Be* should not be in titus-kube-common. I recommend starting off with a map in titus-agent-controllers.

**Comment by MyUmmaGumma** [comment]
> > > 1. This configuration should be a CRD
> > > 2. Are you not going to overwrite the sgs / subnets on the pod?
> > 
> > 
> > I am following @solarkennedy 's comment here (which I might have misunderstood) https://jira.netflix.net/browse/HN-21?focusedCommentId=5172180&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-5172180
> > I planned to add the changes here and then overwrite the sgs and subnets in the titus-agent-controller. Have I misunderstood?
> 
> Yea I think you misunderstood. We can use the existing annotations to _setting_ SG,sub, we don't need new annotations.
> 
> Config for what those settings should _Be_ should not be in titus-kube-common. I recommend starting off with a map in titus-agent-controllers.

got it thanks!

**Pull request closed without merging**
